services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HotelManagement
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hotel-net

volumes:
  mysql_data:

networks:
  hotel-net:
